---
- name: playbook01 medo tasks
  hosts: myrouters
  gather_facts: yes
  vars:
    IP: "{{IP2}}"
    B: "MCIT"
    H: "{{inventory_hostname}}"
  tasks:
    - name: T1 task01 doooooooo print facts
      debug:
        var: ansible_facts

    - name: from out yaml
      import_tasks: cusers.yml
      vars:
        U: admin3
        
    - name: from out yml
      import_tasks: setip.yml


    - name: T6 Apply the provided configuration
      cisco.ios.ios_hostname:
        config:
          hostname: "{{H}}"
        state: merged



  handlers:
    - name: "T3 banner"
      cisco.ios.ios_banner:
        banner: login
        text: |
          this is {{inventory_hostname}} login banner
          that contains a multiline
          string
        state: present

    - name: "T5 up"
      cisco.ios.ios_interfaces:
        config:
        - name: GigabitEthernet2
          enabled: true


